### ISSUE TITLE
Milestone 1: Registration and Proposal

### ISSUE THREAD

**Issue by LER0ever** [CSE230-FA21-Team/Project#2]
## Brainstorm & Write-up
- [x] Setup GitHub project and add basic information (#1 )
- [x] Brainstorm project ideas
- [x] Write project proposal in README

## Proposal Submission
- [x] Rename organization: [here](https://github.com/organizations/CSE230-FA21-Team/settings/profile)
- [x] Rename project: [here](https://github.com/CSE230-FA21-Team/Project/settings)
- [x] Submit project proposal [here](https://docs.google.com/forms/d/e/1FAIpQLScR61QVsiLGSGj2TNwV2T7gprClWqkNbsqUGxN1gCzytgxaEQ/viewform) 

## Project Setup
- [x] Initialize with Haskell project template
- [x] Setup Continuous Integration to build & test every commit
- [ ] Add simple test and finalize folder structures
